ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
[ERROR] [1729762336.237394, 23.566000]: Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)

FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/root/ros1_ws/src/robot_pkg/script/node/MS_maze_search_node.py", line 212, in __init__
    CheckErrP(self._lib),

  File "/root/ros1_ws/src/robot_pkg/script/node/MS_main.py", line 1245, in __init__
    self._lib["com"].openArduino()

  File "/root/ros1_ws/src/robot_pkg/script/lib/lib_com.py", line 132, in openArduino
    self.Ser=serial.Serial('/dev/ttyACM0',9600,timeout=3)

  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()

  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))

serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

pygame 2.6.1 (SDL 2.28.4, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
„Ç≠„Éº„Éú„Éº„ÉâÊìç‰Ωú„ÅåÊúâÂäπ„Åß„Åô„ÄÇ
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ros1_ws/src/robot_pkg/script/node/MS_maze_search_node.py", line 317, in <module>
    state_machine = StateMachine()
  File "/root/ros1_ws/src/robot_pkg/script/node/MS_maze_search_node.py", line 212, in __init__
    CheckErrP(self._lib),
  File "/root/ros1_ws/src/robot_pkg/script/node/MS_main.py", line 1245, in __init__
    self._lib["com"].openArduino()
  File "/root/ros1_ws/src/robot_pkg/script/lib/lib_com.py", line 132, in openArduino
    self.Ser=serial.Serial('/dev/ttyACM0',9600,timeout=3)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
[31m[MS_maze_search_node-1] process has died [pid 36049, exit code 1, cmd /root/ros1_ws/src/robot_pkg/script/node/MS_maze_search_node.py __name:=MS_maze_search_node __log:=/root/.ros/log/c81695a0-91ea-11ef-98eb-0242ac110002/MS_maze_search_node-1.log].
log file: /root/.ros/log/c81695a0-91ea-11ef-98eb-0242ac110002/MS_maze_search_node-1*.log[0m
... logging to /root/.ros/log/c81695a0-91ea-11ef-98eb-0242ac110002/roslaunch-54a6a5906e84-36028.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
]2;/root/ros1_ws/src/robot_pkg/launch/robot_and_interfaceV.launch
[1mstarted roslaunch server http://54a6a5906e84:41161/[0m

SUMMARY
========

PARAMETERS
 * /MiniMap: True
 * /exp_type: ee
 * /random: False
 * /rosdistro: noetic
 * /rosversion: 1.17.0

NODES
  /
    MS_maze_search_node (robot_pkg/MS_maze_search_node.py)

[1mROS_MASTER_URI=http://localhost:11311[0m
]2;/root/ros1_ws/src/robot_pkg/launch/robot_and_interfaceV.launch http://localhost:11311
[1mprocess[MS_maze_search_node-1]: started with pid [36049][0m
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
[1mdone[0m
